server:
  port: 8888

spring:
  application:
    name: spring-app-config-server
  cloud:
    config:
      server:
        git:
          uri: http://localhost:880/fsrcodefsr/config-repo.git
          username: fsrcodefsr
          password: password # Replace with your actual GitLab password


